export { default as Header} from './header/Header'
export { default as About} from './about/About'
export { default as Ourwork} from './ourwork/Ourwork'
export { default as Contact} from './contact/Contact'
export { default as Footer} from './footer/Footer'
export { default as Work} from './works/work'
export { default as Cancer } from './cancer/cancer'
export { default as Number } from './number/number'
export { default as Text } from './text/text'
export {default as Gilbert } from './gilbert/gilbert'
export { default as Ocr } from './Ocr/Ocr'
